FROM golang:1.14-alpine

RUN apk update
RUN apk add git

RUN mkdir /app

COPY . /app

WORKDIR /app

ENV GOPATH=/app

RUN go get github.com/joho/godotenv

RUN go build -o main ./src

CMD ["/app/main" ]
